In [75]:
import pandas as pd

In [76]:
#leemos el dataset
df = pd.read_csv("maternal-health-risk.csv")
df.tail()

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

In [77]:
df.info()
#info general del dataset, vemos que no hay datos nulos

<class 'pandas.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          1014 non-null   int64
 1   SystolicBP   1014 non-null   int64
 2   DiastolicBP  1014 non-null   int64
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64
 6   RiskLevel    1014 non-null   str
dtypes: float64(2), int64(4), str(1)
memory usage: 55.6 KB

In [78]:
#esto para ver los datos duplicados
df.duplicated().sum()
#podemos observar 562 datos duplicados

np.int64(562)

In [79]:
#limpiamos los duplicados
# drop_duplicates() los borra, y reset_index() acomoda los números de las filas para que no queden huecos
df_limpio = df.drop_duplicates().reset_index(drop=True)

In [80]:
df_limpio.duplicated().sum() #aca visualizamos el dataset limpio, y lo guardamos en una nueva variable llamada df_limoio

np.int64(0)

In [81]:
df.shape #visualizamos cuantas filas y columnas tiene el dataset

(1014, 7)

In [82]:
df_limpio.shape #visualizamos cuantas filas y columnas tiene el nuevo dataset

(452, 7)

In [83]:
df_limpio.columns #buscamos nuestra variable objetivo, en este caso, tomamos RiskLevel que es lo que nos interesa, medir el nivel de riesgo

Index(['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate',
       'RiskLevel'],
      dtype='str')

In [84]:
df_limpio["RiskLevel"].unique() #vemos qu elos niveles de riesgo se dividen en, high low y mid (supongo que alto, bajo y medio)

<StringArray>
['high risk', 'low risk', 'mid risk']
Length: 3, dtype: str

In [85]:
df_limpio["RiskLevel"].map({
    "low risk": 0,
    "mid risk": 1,
    "high risk": 2
})

0      2
1      2
2      2
3      2
4      0
      ..
447    1
448    0
449    0
450    1
451    0
Name: RiskLevel, Length: 452, dtype: int64

In [86]:
df_limpio["RiskLevel"] = df_limpio["RiskLevel"].map({
    "low risk": 0,
    "mid risk": 1,
    "high risk": 2
})
df_limpio.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86          2
1   35         140           90  13.0      98.0         70          2
2   29          90           70   8.0     100.0         80          2
3   30         140           85   7.0      98.0         70          2
4   35         120           60   6.1      98.0         76          0